### ISSUE TITLE
If workspaces are defined as an object than fast-glob fails

### ISSUE THREAD

**Issue by almeynman** [ripeworks/workspace-pack#6]
Hey! Awesome work!

If in package.json you define workspaces as 
```
  "workspaces": {
    "packages": ["*"]
  },
```

instead of 
```
  "workspaces": ["*"]

```

then `workspace-pack` fails with 

```
/Users/almeynman/.config/yarn/global/node_modules/fast-glob/out/index.js:66
    throw new TypeError('Patterns must be a string or an array of strings');
    ^

TypeError: Patterns must be a string or an array of strings
    at assertPatternsInput (/Users/almeynman/.config/yarn/global/node_modules/fast-glob/out/index.js:66:11)
    at Function.sync (/Users/almeynman/.config/yarn/global/node_modules/fast-glob/out/index.js:14:5)
    at Object.<anonymous> (/Users/almeynman/.config/yarn/global/node_modules/workspace-pack/bin/index.js:32:28)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by tamagokun** [comment]
this is fixed in master
